version: '3'
services: 
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g:latest
    volumes:
      - oracle-data:/opt/oracle/oradata    
    ports:
      - 1521:1521
      - 5500:5500
volumes:
  oracle-data:
